### ISSUE TITLE
Weird behavior when tapping on the toolbar

### ISSUE THREAD

**Issue by cibeleasreis** [wxik/react-native-rich-editor#101]
I'm facing some issues when selecting/deselecting actions from the toolbar. They don't get enabled/disabled consistently. 
I found this issue at this example too: 
[https://wxik.github.io/react-native-rich-editor/web/
](url)

please see the video below: 
https://vimeo.com/478617581

**Comment by cibeleasreis** [comment]
The SELECTION_CHANGE is not returning the right actions that should be selected. The handler seems broken at editor.js

**Comment by SalehAly01** [comment]
@cibeleasreis I am facing the same issue as well.
When I try to use `italic`, it might enable `bold` with it and when trying to deselect `bold`, it might deselect both `bold` and `italic`.

**Comment by cibeleasreis** [comment]
Hey @SalehAly01 
I found the issue and had a temporary solution for that. 

I just commented the focus function on the editor. Here's my change: 
https://github.com/wxik/react-native-rich-editor/commit/4785ab8c0d07389f289530d716f5ed00fdf7a022

**Comment by Dheyson** [comment]
I got some related issue when selecting and deselecting the a custom icon from the toolbar.

**Comment by SalehAly01** [comment]
Thank you @cibeleasreis 
I did that and it fixed the issue.

**Comment by cristianoccazinsp** [comment]
Still broken for me with 1.5.4

**Comment by stulip** [comment]
Fixed in 1.5.5

**Comment by cristianoccazinsp** [comment]
Not entirely fixed: https://github.com/wxik/react-native-rich-editor/issues/127 with video and example code.
